/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WaitlistDemoRouteImport } from './routes/waitlist-demo'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistDemoRoute = WaitlistDemoRouteImport.update({
  id: '/waitlist-demo',
  path: '/waitlist-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/manage': typeof ManageRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/waitlist-demo': typeof WaitlistDemoRoute
  '/admin/login': typeof AdminLoginRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/manage': typeof ManageRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/waitlist-demo': typeof WaitlistDemoRoute
  '/admin/login': typeof AdminLoginRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/manage': typeof ManageRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/waitlist-demo': typeof WaitlistDemoRoute
  '/admin/login': typeof AdminLoginRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/manage'
    | '/privacy'
    | '/terms'
    | '/waitlist-demo'
    | '/admin/login'
    | '/claim/$token'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/manage'
    | '/privacy'
    | '/terms'
    | '/waitlist-demo'
    | '/admin/login'
    | '/claim/$token'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/manage'
    | '/privacy'
    | '/terms'
    | '/waitlist-demo'
    | '/admin/login'
    | '/claim/$token'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  ManageRoute: typeof ManageRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WaitlistDemoRoute: typeof WaitlistDemoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist-demo': {
      id: '/waitlist-demo'
      path: '/waitlist-demo'
      fullPath: '/waitlist-demo'
      preLoaderRoute: typeof WaitlistDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  ManageRoute: ManageRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WaitlistDemoRoute: WaitlistDemoRoute,
  AdminLoginRoute: AdminLoginRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
